In [22]:
import pandas as pd
df=pd.read_excel(r"C:\Users\HP\Downloads\clean data edited.xlsx")
df

,Last_Watched,Frequent_Watch,Reason_of_Watch,Frequent_Go_Cinema,Factors,underrated geners,Action_Rate,Adventure_Rate,Comedy_Rate,Drama_Rate,...,setup for watching movies at home,usuall way to watch movies at home,favorite Streaming Platform,Age,Major,Gender,Critical Reviews,Friends' Opinions (who already watched it),Internet Sites,TV Entertainment Programs
0,This month,Three or four times,Social media,I don't go to the Cinema,Quality of Story,NaN,5,4,3,2,...,NaN,NaN,NaN,19,Data Science,Female,0,0,0,0
1,This month,Three or four times,Recommended,I don't go to the Cinema,Genre,NaN,4,5,5,1,...,NaN,NaN,NaN,20,Data Science,Male,0,1,0,0
2,Less than a week,Once or twice,Recommended,Once or Twice a year,Quality of Story,NaN,5,5,2,3,...,NaN,NaN,NaN,20,Data Science,Male,0,0,1,0
3,Less than a week,Once or twice,Social Media,Once a month,Quality of Story,NaN,5,4,5,2,...,NaN,NaN,NaN,20,Data Science,Male,0,0,1,0
4,Less than a week,Less than once,Social Media,I don't go to the Cinema,Quality of Story,NaN,3,5,3,3,...,NaN,NaN,NaN,20,Data Science,Female,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,This month,Three or four times,Social Media,Once a month,Quality of Story,Fantasy,3,4,3,3,...,NaN,NaN,NaN,20,Data Science,Female,0,0,0,0
246,Less than a week,Less than once,Trailers,Once a month,Quality of Story,No,1,2,3,1,...,NaN,NaN,NaN,20,Data Science,Female,0,0,0,1
247,Last Month,Once or twice,Internet Sites,Once or Twice a year,Directing,Psychological horror,3,4,4,5,...,NaN,NaN,NaN,20,Data Science,Female,0,0,1,0
248,This month,Three or four times,Trailers,Once or Twice a year,Directing,Musical films,3,4,5,5,...,NaN,NaN,NaN,19,Data Science,Female,0,0,0,0
249,This month,Once or twice,Social Media,Once or Twice a year,Quality of Story,No,2,5,3,5,...,NaN,NaN,NaN,20,Data Science,Female,0,0,0,0

In [23]:
df[['best day(c)','best time(c)']] = df.Going_Cinema.str.split("-",expand=True)
df

,Last_Watched,Frequent_Watch,Reason_of_Watch,Frequent_Go_Cinema,Factors,underrated geners,Action_Rate,Adventure_Rate,Comedy_Rate,Drama_Rate,...,favorite Streaming Platform,Age,Major,Gender,Critical Reviews,Friends' Opinions (who already watched it),Internet Sites,TV Entertainment Programs,best day(c),best time(c)
0,This month,Three or four times,Social media,I don't go to the Cinema,Quality of Story,NaN,5,4,3,2,...,NaN,19,Data Science,Female,0,0,0,0,Weekend,Evening
1,This month,Three or four times,Recommended,I don't go to the Cinema,Genre,NaN,4,5,5,1,...,NaN,20,Data Science,Male,0,1,0,0,Weekend,Evening
2,Less than a week,Once or twice,Recommended,Once or Twice a year,Quality of Story,NaN,5,5,2,3,...,NaN,20,Data Science,Male,0,0,1,0,Weekend,Evening
3,Less than a week,Once or twice,Social Media,Once a month,Quality of Story,NaN,5,4,5,2,...,NaN,20,Data Science,Male,0,0,1,0,Weekend,Evening
4,Less than a week,Less than once,Social Media,I don't go to the Cinema,Quality of Story,NaN,3,5,3,3,...,NaN,20,Data Science,Female,0,0,0,0,Weekend,Evening
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,This month,Three or four times,Social Media,Once a month,Quality of Story,Fantasy,3,4,3,3,...,NaN,20,Data Science,Female,0,0,0,0,Weekday,Evening
246,Less than a week,Less than once,Trailers,Once a month,Quality of Story,No,1,2,3,1,...,NaN,20,Data Science,Female,0,0,0,1,Weekday,Evening
247,Last Month,Once or twice,Internet Sites,Once or Twice a year,Directing,Psychological horror,3,4,4,5,...,NaN,20,Data Science,Female,0,0,1,0,Weekday,Afternoon
248,This month,Three or four times,Trailers,Once or Twice a year,Directing,Musical films,3,4,5,5,...,NaN,19,Data Science,Female,0,0,0,0,Weekend,Afternoon
249,This month,Once or twice,Social Media,Once or Twice a year,Quality of Story,No,2,5,3,5,...,NaN,20,Data Science,Female,0,0,0,0,Weekend,Evening

In [24]:
df.isnull().sum()

Last_Watched                                                                   0
Frequent_Watch                                                                 0
Reason_of_Watch                                                                0
Frequent_Go_Cinema                                                             0
Factors                                                                        0
  underrated geners                                                           71
 Action_Rate                                                                   0
Adventure_Rate                                                                 0
Comedy_Rate                                                                    0
Drama_Rate                                                                     0
 Romance_Rate                                                                  0
Horror_Rate                                                                    0
Sci-fi_Rate                                                                    0
Musical_Rate                                                                   0
Family_Rate                                                                    0
Search_Before_Watch                                                            0
Ads_effect                                                                     0
Usually_Disappoint                                                             0
Cast                                                                           0
Genre                                                                          0
Director                                                                       0
Studio                                                                         0
Reviews                                                                        0
Quality_ Story                                                                 0
Watching_Place                                                                 0
Going_Cinema                                                                 172
Seats and Snacks of the Cinema effect on  enjoying a movie?                  172
Why do you prefer watching movies at home instead of going to the cinema?     83
 setup  for watching movies at home                                           84
 usuall way to watch movies at home                                           83
 favorite Streaming Platform                                                 105
 Age                                                                           0
 Major                                                                         0
 Gender                                                                       28
Critical Reviews                                                               0
Friends' Opinions (who already watched it)                                     0
Internet Sites                                                                 0
TV Entertainment Programs                                                      0
best day(c)                                                                  172
best time(c)                                                                 172
dtype: int64

In [27]:
df[" Gender"]

0      Female
1        Male
2        Male
3        Male
4      Female
        ...
245    Female
246    Female
247    Female
248    Female
249    Female
Name:  Gender, Length: 250, dtype: object

In [31]:
median = df[' Gender'].mode()[0]
df[' Gender'].fillna(median, inplace=True)
df

,Last_Watched,Frequent_Watch,Reason_of_Watch,Frequent_Go_Cinema,Factors,underrated geners,Action_Rate,Adventure_Rate,Comedy_Rate,Drama_Rate,...,favorite Streaming Platform,Age,Major,Gender,Critical Reviews,Friends' Opinions (who already watched it),Internet Sites,TV Entertainment Programs,best day(c),best time(c)
0,This month,Three or four times,Social media,I don't go to the Cinema,Quality of Story,NaN,5,4,3,2,...,NaN,19,Data Science,Female,0,0,0,0,Weekend,Evening
1,This month,Three or four times,Recommended,I don't go to the Cinema,Genre,NaN,4,5,5,1,...,NaN,20,Data Science,Male,0,1,0,0,Weekend,Evening
2,Less than a week,Once or twice,Recommended,Once or Twice a year,Quality of Story,NaN,5,5,2,3,...,NaN,20,Data Science,Male,0,0,1,0,Weekend,Evening
3,Less than a week,Once or twice,Social Media,Once a month,Quality of Story,NaN,5,4,5,2,...,NaN,20,Data Science,Male,0,0,1,0,Weekend,Evening
4,Less than a week,Less than once,Social Media,I don't go to the Cinema,Quality of Story,NaN,3,5,3,3,...,NaN,20,Data Science,Female,0,0,0,0,Weekend,Evening
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,This month,Three or four times,Social Media,Once a month,Quality of Story,Fantasy,3,4,3,3,...,NaN,20,Data Science,Female,0,0,0,0,Weekday,Evening
246,Less than a week,Less than once,Trailers,Once a month,Quality of Story,No,1,2,3,1,...,NaN,20,Data Science,Female,0,0,0,1,Weekday,Evening
247,Last Month,Once or twice,Internet Sites,Once or Twice a year,Directing,Psychological horror,3,4,4,5,...,NaN,20,Data Science,Female,0,0,1,0,Weekday,Afternoon
248,This month,Three or four times,Trailers,Once or Twice a year,Directing,Musical films,3,4,5,5,...,NaN,19,Data Science,Female,0,0,0,0,Weekend,Afternoon
249,This month,Once or twice,Social Media,Once or Twice a year,Quality of Story,No,2,5,3,5,...,NaN,20,Data Science,Female,0,0,0,0,Weekend,Evening

In [32]:
df.isnull().sum()

Last_Watched                                                                   0
Frequent_Watch                                                                 0
Reason_of_Watch                                                                0
Frequent_Go_Cinema                                                             0
Factors                                                                        0
  underrated geners                                                           71
 Action_Rate                                                                   0
Adventure_Rate                                                                 0
Comedy_Rate                                                                    0
Drama_Rate                                                                     0
 Romance_Rate                                                                  0
Horror_Rate                                                                    0
Sci-fi_Rate                                                                    0
Musical_Rate                                                                   0
Family_Rate                                                                    0
Search_Before_Watch                                                            0
Ads_effect                                                                     0
Usually_Disappoint                                                             0
Cast                                                                           0
Genre                                                                          0
Director                                                                       0
Studio                                                                         0
Reviews                                                                        0
Quality_ Story                                                                 0
Watching_Place                                                                 0
Going_Cinema                                                                 172
Seats and Snacks of the Cinema effect on  enjoying a movie?                  172
Why do you prefer watching movies at home instead of going to the cinema?     83
 setup  for watching movies at home                                           84
 usuall way to watch movies at home                                           83
 favorite Streaming Platform                                                 105
 Age                                                                           0
 Major                                                                         0
 Gender                                                                        0
Critical Reviews                                                               0
Friends' Opinions (who already watched it)                                     0
Internet Sites                                                                 0
TV Entertainment Programs                                                      0
best day(c)                                                                  172
best time(c)                                                                 172
dtype: int64

In [34]:
df.to_csv('data.csv')